#!/bin/bash

# SETUP_BINANCE_TESTNET.sh - Configuración paso a paso para Binance Testnet
# Para validación real del sistema mejorado con $100 virtual

echo "🚀 CONFIGURACIÓN BINANCE TESTNET - TRADING REAL"
echo "================================================================"
echo "Objetivo: Conectar sistema mejorado a Binance Testnet (sandbox)"
echo "Capital: $100 virtual para validación"
echo "================================================================"

echo ""
echo "📋 PASO 1: CREAR CUENTA EN BINANCE TESTNET"
echo "----------------------------------------"
echo "1. Visitar: https://testnet.binance.vision"
echo "2. Hacer clic en 'Register' o 'Login'"
echo "3. Usar email válido (se enviará código de verificación)"
echo "4. Completar registro"
echo ""
echo "💡 CONSEJO: Usa un email que puedas verificar inmediatamente"

echo ""
echo "📋 PASO 2: GENERAR API KEYS"
echo "----------------------------------------"
echo "1. Una vez logueado, ir a: API Management"
echo "2. Hacer clic en 'Create API'"
echo "3. Nombrar la API: 'OpenClaw-Trading-System'"
echo "4. PERMISOS IMPORTANTES:"
echo "   ✅ Enable Reading"
echo "   ✅ Enable Spot & Margin Trading"
echo "   ❌ NO habilitar Withdrawals (seguridad)"
echo "5. Hacer clic en 'Create'"
echo "6. ANOTAR:"
echo "   - API Key: ________________"
echo "   - Secret Key: ________________"
echo ""
echo "⚠️  ADVERTENCIA: Las Secret Keys solo se muestran una vez"
echo "   Guardarlas en lugar seguro inmediatamente"

echo ""
echo "📋 PASO 3: CONFIGURAR VARIABLES DE ENTORNO"
echo "----------------------------------------"
echo "Una vez tengas las API keys, ejecutar:"
echo ""
echo "export BINANCE_TESTNET_API_KEY='TU_API_KEY_AQUI'"
echo "export BINANCE_TESTNET_SECRET_KEY='TU_SECRET_KEY_AQUI'"
echo ""
echo "O crear archivo .env en /home/ubuntu/.openclaw/workspace/trading/real_trading/:"
echo ""
echo "BINANCE_TESTNET_API_KEY=TU_API_KEY_AQUI"
echo "BINANCE_TESTNET_SECRET_KEY=TU_SECRET_KEY_AQUI"

echo ""
echo "📋 PASO 4: TEST DE CONEXIÓN"
echo "----------------------------------------"
echo "Ejecutar el test de conexión:"
echo ""
echo "cd /home/ubuntu/.openclaw/workspace/trading/real_trading"
echo "python3 test_connection.py"
echo ""
echo "Deberías ver: '✅ Conexión exitosa a Binance Testnet'"

echo ""
echo "📋 PASO 5: DEPOSITAR CAPITAL VIRTUAL"
echo "----------------------------------------"
echo "1. En Binance Testnet, ir a 'Wallet'"
echo "2. Buscar USDT"
echo "3. Hacer clic en 'Deposit'"
echo "4. Seleccionar 'Test Network'"
echo "5. Depositar $100 USDT virtuales"
echo ""
echo "💡 CONSEJO: También puedes depositar BTC/ETH virtuales para testing"

echo ""
echo "📋 PASO 6: EJECUTAR SISTEMA DE TRADING REAL"
echo "----------------------------------------"
echo "Una vez configurado, ejecutar:"
echo ""
echo "cd /home/ubuntu/.openclaw/workspace/trading/real_trading"
echo "python3 real_trading_system.py"
echo ""
echo "El sistema ejecutará automáticamente:"
echo "- 24 horas de trading"
echo "- Cada 60 minutos genera señales"
echo "- Ejecuta trades REALES en sandbox"
echo "- Dashboard en tiempo real"

echo ""
echo "================================================================"
echo "🎯 RESUMEN DE CONFIGURACIÓN"
echo "================================================================"
echo "1. ✅ Crear cuenta Binance Testnet"
echo "2. ✅ Generar API keys con permisos limitados"
echo "3. ✅ Configurar variables de entorno"
echo "4. ✅ Test de conexión"
echo "5. ✅ Depositar $100 USDT virtuales"
echo "6. ✅ Ejecutar sistema de trading real"
echo ""
echo "⏰ TIEMPO ESTIMADO: 15-20 minutos"
echo "💰 CAPITAL: $100 virtual (sin riesgo real)"
echo "🎯 OBJETIVO: Validación real del sistema mejorado"
echo "================================================================"

echo ""
echo "💡 CONSEJOS FINALES:"
echo "- Usa contraseña segura para Binance Testnet"
echo "- Guarda API keys en lugar seguro"
echo "- Monitorea primeros trades manualmente"
echo "- Revisa logs en /home/ubuntu/.openclaw/workspace/trading/real_trading/logs/"
echo ""
echo "🚀 ¡LISTO PARA LA VALIDACIÓN REAL!"